### ISSUE TITLE
Make reference/shortcuts use YAML data

### ISSUE THREAD

**Issue by nkrkv** [xodio/xod-docs#40]
Currently, the [shortcuts reference](https://github.com/xodio/xod-docs/tree/master/docs/reference/shortcuts) list items through plain HTML tables.

The items are a highly structured data that might be defined in a YAML file. This way is preferable because if we want to make a slight change in the HTML markup, we are in trouble: changes in every line of the table across all translations will be required.

To support translations the YAML source can have a separate description field for every language:

```yaml
- shortcut:
    mac: ⌘ N
    pc: Ctrl+N
    action:
      EN: "New patch"
      DE: "Neu patch"
      RU: "Новый патч"
```
